language: ruby
rvm: 2.6.3
sudo: false
addons:
  postgresql: "9.4"
script: bundle exec rake test
before_script:
  - psql -c 'create database active_median_test;' -U postgres
  - mysql -e 'create database active_median_test;'
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: "10.3"
