dist: xenial
language: ruby
rvm: 2.6.3
script: bundle exec rake test
services:
  - postgresql
before_script:
  - createdb active_median_test
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: "10.3"
      before_script:
        - mysql -e 'create database active_median_test;'
    - gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
      before_script:
        - echo "Skipping createdb"
