language: ruby
rvm: 2.6.3
sudo: false
addons:
  postgresql: "9.4"
script: bundle exec rake test
before_script:
  - createdb active_median_test
  - mysqladmin create active_median_test
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: "10.3"
    - gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
