dist: bionic
language: ruby
rvm: 2.6
script: bundle exec rake test
services:
  - postgresql
addons:
  postgresql: 10
before_script:
  - createdb active_median_test
notifications:
  email:
    on_success: never
    on_failure: change
gemfile:
  - Gemfile
  - test/gemfiles/activerecord52.gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
matrix:
  include:
    - gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: "10.3"
      before_script:
        - mysqladmin create active_median_test
        - mysql -e 'create user travis@localhost;'
        - mysql -e 'grant all on *.* to travis@localhost;'
    - gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
      before_script:
        - echo "Skipping createdb"
