dist: bionic
language: ruby
script: bundle exec rake test
services:
  - postgresql
addons:
  postgresql: 10
before_script:
  - createdb active_median_test
notifications:
  email:
    on_success: never
    on_failure: change
jobs:
  include:
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.6
      gemfile: test/gemfiles/activerecord52.gemfile
    - rvm: 2.5
      gemfile: test/gemfiles/activerecord51.gemfile
    - rvm: 2.4
      gemfile: test/gemfiles/activerecord50.gemfile
    - rvm: 2.7
      gemfile: test/gemfiles/mysql2.gemfile
      env: ADAPTER=mysql2
      addons:
        mariadb: "10.3"
      before_script:
        - mysqladmin create active_median_test
        - mysql -e 'create user travis@localhost;'
        - mysql -e 'grant all on *.* to travis@localhost;'
    - rvm: 2.7
      gemfile: test/gemfiles/mongoid7.gemfile
      services:
        - mongodb
      before_script:
        - echo "Skipping createdb"
